name: Assign tech writers

on: 
  pull_request: 
    types: [labeled]
jobs:
  assign_tech_writers:
    if: {{github.event.label.name == 'doc-changes'}}

    steps:
      - name: assign techwriters to PR
        uses: hkusu/review-assign-action@v1
        with:
          assignees: egilmorez
